## Section A: Data Structures & Control Structures

In [4]:
# 1. List operations

# Created list of 5 intergers
list_ele = [20, 40, 30, 10, 50]
print("Created List:",list_ele)

# append() - adds an element to the end of the list
list_ele.append(60)
print("After append:",list_ele)

# extend() - adds multiple elements at once
list_ele.extend([70,80])
print("After Extend:",list_ele)

# insert() - Inserts an element at a specific position
list_ele.insert(2, 25)
print("After insert:", list_ele)

# remove() - Removes the first occurrence of a specified element
list_ele.remove(25)
print("After remove:", list_ele)

# pop() - Removes and returns the last element
list_ele.pop()
print("After pop:", list_ele)

# index() - Returns the index of a value
print("Index of 30:", list_ele.index(30))

# count() - Counts how many times a value occurs
print("Count of 20:", list_ele.count(20))

# sort() - Sorts the list in ascending order
list_ele.sort()
print("After sort:", list_ele)

# reverse() - Reverses the list order
list_ele.reverse()
print("After reverse:", list_ele)

# clear() - Removes all items from the list
list_ele.clear()
print("After clear:", list_ele)

Created List: [20, 40, 30, 10, 50]
After append: [20, 40, 30, 10, 50, 60]
After Extend: [20, 40, 30, 10, 50, 60, 70, 80]
After insert: [20, 40, 25, 30, 10, 50, 60, 70, 80]
After remove: [20, 40, 30, 10, 50, 60, 70, 80]
After pop: [20, 40, 30, 10, 50, 60, 70]
Index of 30: 2
Count of 20: 1
After sort: [10, 20, 30, 40, 50, 60, 70]
After reverse: [70, 60, 50, 40, 30, 20, 10]
After clear: []


In [5]:
# 2. Tuple

student_names = ("Alice", "Bob", "Charlie")

student_names[1] = "David"  #changing second name

print("Tuple:", student_names)

# Tuples are immutable, so you cannot modify their elements
# Trying to change a value will raise an error

TypeError: 'tuple' object does not support item assignment

In [6]:
# 3. Set

Set_elements = {1, 1, 2, 2, 3, 4, 5, 5, 6, 7}
print("Set of elements:",Set_elements)

# Duplicate elements are automatically removed in a set.
# Sets store only unique elements, so repeated elements are ignored.

Set of elements: {1, 2, 3, 4, 5, 6, 7}


In [7]:
# 4. Dictionary

person = {"name": "John", "age": 25, "city": "Hyderabad"}

# Updating age value
person["age"] = 26

# Adding a new key-value pair into dictionary
person["email"] = "john@example.com"

print("Updated Dictionary:", person)

Updated Dictionary: {'name': 'John', 'age': 26, 'city': 'Hyderabad', 'email': 'john@example.com'}


In [8]:
# 5. Is person eligible to vote or not?

age = 17

if age >= 18:
    print("Eligible to vote.")
else:
    print("Not eligible to vote")

# Assigned 17 to the variable age
# 17 is lessthan 18, the person is not eligible to vote

Not eligible to vote


In [9]:
# 6. Grade

marks = 76

if marks >= 90:
    grade = 'A'
elif marks >= 75:
    grade = 'B'
elif marks >= 50:
    grade = 'C'
else:
    grade = 'Fail'

print("Grade:", grade)

Grade: B


In [10]:
# 7. Number

num = 7

if num > 0:
    if num % 2 == 0:
        print(num, "is positive and even.")
    else:
        print(num, "is positive but odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

# i assigned value 7 to the variable num
# entered 7 is positive number and it does not satisfying the condition(num%2==0) so it is odd number

7 is positive but odd.


## Section B: Numpy

In [11]:
# 8. Creating an array

# importing numpy library
import numpy as np

# Scalar : In NumPy, Scalar means a single value, not an array of many elements.
scalar = np.array(5)
print("Scalar:",scalar)

# 1D Array : Elements are stored in single row with values 1 to 5.
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

# 2D Array (2x3) : Elements are stored in 2 dimensional array with 2 rows and 3 columns
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("2D Array:\n", arr_2d)

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


In [12]:
# 9. 

rand_arr = np.random.randint(0, 100, (4, 4))
print("Random 4x4 Array:\n", rand_arr)

# This np.random.randint(low, high, size) creates a 4x4 array (4 rows × 4 columns) 
# and each value is randomly generated integer between 0 and 100.
# The output changes every time when we run it because random numbers differ on each execution.

Random 4x4 Array:
 [[32 27 50 16]
 [92 58 44 59]
 [68 40 89 30]
 [85 72 39 96]]


In [13]:
# 10. 

# Imported pandas
import pandas as pd

# Created a 3x3 numpy array
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Converting the 2D numpy array into a pandas DataFrame
df = pd.DataFrame(data, columns=['A', 'B', 'C']) #data is stored in table formate with column names
print("DataFrame from NumPy Array:\n", df)

DataFrame from NumPy Array:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


## Section C: Exploring Pandas

In [14]:
# 11. 

data = {
    'Name': ['Lahari', 'Tolusuri', 'Kiran', 'Meena', 'Rahul', 'Sneha', 'Kiran', 'Asha', 'Vikram', 'Neha'],
    'Age': [22, 24, 23, 25, 26, 22, 23, 22, 27, 25],
    'City': ['Hyderabad', 'Chennai', 'Delhi', 'Mumbai', 'Hyderabad', 'Pune', 'Delhi', 'Hyderabad', 'Chennai', 'Pune'],
    'Salary': [45000, 50000, 48000, 52000, 55000, None, 48000, 45000, 50000, None]
}

df = pd.DataFrame(data)
print("Created DataFrame:\n", df)

# dataframe is created with rows and columns

Created DataFrame:
        Name  Age       City   Salary
0    Lahari   22  Hyderabad  45000.0
1  Tolusuri   24    Chennai  50000.0
2     Kiran   23      Delhi  48000.0
3     Meena   25     Mumbai  52000.0
4     Rahul   26  Hyderabad  55000.0
5     Sneha   22       Pune      NaN
6     Kiran   23      Delhi  48000.0
7      Asha   22  Hyderabad  45000.0
8    Vikram   27    Chennai  50000.0
9      Neha   25       Pune      NaN


In [15]:
print("Information about data:")
df.info() 

# .info() method shows column names, no.of non-missing values,data types of each column

Information about data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [16]:
Describe = df.describe()
print("Summary:\n",Describe)

# .describe() method Shows statistical summary of numeric columns in DataFrame 
# like (count, mean, std, min, max, etc).

Summary:
              Age       Salary
count  10.000000      8.00000
mean   23.900000  49125.00000
std     1.791957   3399.05449
min    22.000000  45000.00000
25%    22.250000  47250.00000
50%    23.500000  49000.00000
75%    25.000000  50500.00000
max    27.000000  55000.00000


In [17]:
print(df[['Name', 'City']])  
# Selecting specific columns from dataframe

       Name       City
0    Lahari  Hyderabad
1  Tolusuri    Chennai
2     Kiran      Delhi
3     Meena     Mumbai
4     Rahul  Hyderabad
5     Sneha       Pune
6     Kiran      Delhi
7      Asha  Hyderabad
8    Vikram    Chennai
9      Neha       Pune


In [18]:
df = df.drop('City', axis=1) 
print(df)

# drop() method is used to drop the city column from dataframe and
# axis=1 means column-wise drop

       Name  Age   Salary
0    Lahari   22  45000.0
1  Tolusuri   24  50000.0
2     Kiran   23  48000.0
3     Meena   25  52000.0
4     Rahul   26  55000.0
5     Sneha   22      NaN
6     Kiran   23  48000.0
7      Asha   22  45000.0
8    Vikram   27  50000.0
9      Neha   25      NaN


In [19]:
mean_salary = df['Salary'].mean() 
df['Salary'] = df['Salary'].fillna(mean_salary)
print(df)

# .mean() method will Calculate the average of Salary column and 
# .fillna() replace the NaN with mean value

       Name  Age   Salary
0    Lahari   22  45000.0
1  Tolusuri   24  50000.0
2     Kiran   23  48000.0
3     Meena   25  52000.0
4     Rahul   26  55000.0
5     Sneha   22  49125.0
6     Kiran   23  48000.0
7      Asha   22  45000.0
8    Vikram   27  50000.0
9      Neha   25  49125.0


In [20]:
df = df.drop_duplicates()
print(df)

# .drop_duplicates() method will remove duplicate rows from dataframe

       Name  Age   Salary
0    Lahari   22  45000.0
1  Tolusuri   24  50000.0
2     Kiran   23  48000.0
3     Meena   25  52000.0
4     Rahul   26  55000.0
5     Sneha   22  49125.0
7      Asha   22  45000.0
8    Vikram   27  50000.0
9      Neha   25  49125.0
